#!/bin/sh

echo_task() {
  printf "\033[0;34m--> %s\033[0m\n" "$*"
}

error() {
  printf "\033[0;31m%s\033[0m\n" "$*" >&2
  exit 1
}

set -eu

retry_count="${DOTFILES_RETRY_COUNT:-3}"
retry_delay="${DOTFILES_RETRY_DELAY:-5}"
attempt=1
success=false

if chezmoi="$(command -v chezmoi 2>/dev/null)"; then
  :
else
  bin_dir="${HOME}/.local/bin"
  chezmoi="${bin_dir}/chezmoi"
  mkdir -p "${bin_dir}"
  echo_task "Installing chezmoi to ${chezmoi}"
  if command -v curl >/dev/null 2>&1; then
    sh -c "$(curl -fsLS https://get.chezmoi.io/lb)" -- -b "${bin_dir}"
  elif command -v wget >/dev/null 2>&1; then
    sh -c "$(wget -qO- https://get.chezmoi.io/lb)" -- -b "${bin_dir}"
  else
    error "To install chezmoi, you must have curl or wget."
  fi
fi

# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
script_dir="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
source_dir=""

if [ -n "${DOTFILES_SOURCE-}" ]; then
  source_dir="${DOTFILES_SOURCE}"
elif [ -f "${script_dir}/.chezmoiversion" ]; then
  source_dir="${script_dir}"
elif [ -f "${script_dir}/home/.chezmoiversion" ] || [ -f "${script_dir}/.chezmoiroot" ]; then
  source_dir="${script_dir}"
fi

set -- init

if [ -n "${DOTFILES_ONE_SHOT-}" ]; then
  set -- "$@" --one-shot
else
  set -- "$@" --apply
fi

if [ -n "${DOTFILES_DEBUG-}" ]; then
  set -- "$@" --debug
fi

if [ -n "${DOTFILES_VERBOSE-}" ]; then
  set -- "$@" --verbose
fi

if [ -n "${DOTFILES_CHEZMOI_INCLUDE-}" ]; then
  set -- "$@" --include "${DOTFILES_CHEZMOI_INCLUDE}"
fi

if [ -n "${DOTFILES_CHEZMOI_EXCLUDE-}" ]; then
  set -- "$@" --exclude "${DOTFILES_CHEZMOI_EXCLUDE}"
fi

if [ -n "${DOTFILES_NO_TTY-}" ]; then
  set -- "$@" --no-tty
fi

if [ -n "${source_dir}" ]; then
  echo_task "Using ${source_dir} as chezmoi source"
  set -- "$@" --source "${source_dir}"
else
  set -- "$@" "${DOTFILES_REPO:-github.com/${DOTFILES_USER:-kitos9112}/dotfiles}"
fi

while [ "$attempt" -le "$retry_count" ]; do
  echo_task "Attempt $attempt: Running chezmoi $*"

  if "${chezmoi}" "$@"; then
    success=true
    break
  else
    echo_task "chezmoi init failed. Retrying in ${retry_delay} seconds..."
    sleep "$retry_delay"
    attempt=$((attempt+1))
  fi
done

if [ "$success" = false ]; then
  error "chezmoi init failed after $retry_count attempts."
fi
