[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
exact = true
refreshPeriod = "72h"

[".oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
exact = true
refreshPeriod = "24h"

[".oh-my-zsh-custom/plugins/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions.git"
exact = true
refreshPeriod = "24h"

[".oh-my-zsh-custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
exact = true
refreshPeriod = "24h"

[".tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux.git"
exact = true
refreshPeriod = "24h"

[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv.git"
exact = true
refreshPeriod = "24h"

[".asdf"]
type = "git-repo"
url = "https://github.com/asdf-vm/asdf.git"
exact = true
refreshPeriod = "24h"
