[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
exact = true
refreshPeriod = "72h"

[".oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
exact = true
refreshPeriod = "24h"

[".oh-my-zsh-custom/plugins/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions.git"
exact = true
refreshPeriod = "24h"

[".oh-my-zsh-custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
exact = true
refreshPeriod = "24h"

[".tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux.git"
exact = true
refreshPeriod = "24h"

[".asdf"]
type = "git-repo"
url = "https://github.com/asdf-vm/asdf.git"
exact = true
refreshPeriod = "24h"

[".fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.git"
exact = true
refreshPeriod = "24h"

[".config/wireshark_profiles"]
type = "git-repo"
url = "https://github.com/amwalding/wireshark_profiles.git"
exact = true
refreshPeriod = "72h"

[".local/share/fonts"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.tar.xz"
include = ["*.otf", ".ttf"]
exact = true
refreshPeriod = "168h"

[".config/alacritty/themes"]
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme"
exact = true
refreshPeriod = "72h"

{{ if not .is_root -}}
[".apps/vscode"]
type = "archive"
url = "https://code.visualstudio.com/sha/download?version=1.87.2&os={{ .chezmoi.os }}-{{ if eq .chezmoi.arch "amd64" }}x64{{ else }}arm64{{ end }}"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".go"]
type = "archive"
url = "https://go.dev/dl/go1.22.1.{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

{{ end -}}
