name: Schedule - Nightly Acceptance Tests

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "true"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 0 * * *"

env:
  LOG_LEVEL: info

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - fedora-41
          - fedora-42

    steps:
      - name: Get the current date
        id: date
        run: echo "DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Override default config from dispatch variables
        run: |
          echo "DRY_RUN=${{ github.event.inputs.dryRun || env.DRY_RUN }}" >> "$GITHUB_ENV"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          driver: docker
          context: .
          platforms: linux/amd64
          file: ./tests/${{ matrix.os }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.os }}-${{ env.DATE }}

      - name: Notify about failure
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: "🟡 [Dotfiles] - Nightly Build Failed"
          message: "Github Actions Nightly dotfiles build failed. Take a look"
          url_title: "View on Github"
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          priority: "-1" # low priority - no sound or vibration generated
        if: failure()
